<?php
defined('_JEXEC') or die;

use Joomla\CMS\Language\Text;

/**
 * Layout variables
 * -----------------
 * @var   string  $editorName  The ID of the editor textarea (passed from ytvideobtn.php)
 * @var   array   $params      The plugin parameters (if needed, passed from ytvideobtn.php)
 */

// This layout now only provides the *content* for the modal body and footer.
// The modal shell (div.modal.fade, .modal-dialog, .modal-content) will be generated by HTMLHelper::_('bootstrap.renderModal')
// Or, if renderModal is not used, this file would contain the full modal structure as before,
// but without the self-injecting/event-binding script.

// For now, let's assume this file should output the *full* modal structure,
// and ytvideobtn.php will find a way to place this output into the document body.
// The JavaScript will be handled separately by ytvideobtn.php.
?>
<div id="ytvideo-modal" class="joomla-modal modal fade" role="dialog" aria-labelledby="ytvideo-modal-title" aria-hidden="true" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ytvideo-modal-title"><?php echo Text::_('PLG_EDITORS-XTD_YTVIDEOBTN_MODAL_TITLE'); ?></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<?php echo Text::_('JLIB_HTML_BEHAVIOR_CLOSE'); ?>"></button>
            </div>
            <div class="modal-body">
                <div class="form-vertical">
                    <div class="mb-3">
                        <label for="ytvideo_url_field" class="form-label"><?php echo Text::_('PLG_EDITORS-XTD_YTVIDEOBTN_LABEL_URL'); ?></label>
                        <input name="ytvideourl" id="ytvideo_url_field" value="" class="form-control" type="text">
                    </div>
                    <div class="mb-3">
                        <label for="ytvideo_ratio_field" class="form-label"><?php echo Text::_('PLG_EDITORS-XTD_YTVIDEOBTN_LABEL_RATIO'); ?></label>
                        <select name="ytvideoratio" id="ytvideo_ratio_field" class="form-select">
                            <option value="4-3">4:3 (TV)</option>
                            <option value="5-3">5:3 (Wide TV)</option>
                            <option value="16-9" selected>16:9 (Standard YouTube, HD)</option>
                            <option value="167-9">16.7:9 (Standard films)</option>
                            <option value="18-9">18:9 (iPhone)</option>
                            <option value="199-9">19.9:9 (Wide 70mm)</option>
                            <option value="235-1">2.35:1 (Panavision)</option>
                            <option value="255-1">2.55:1 (Cinemascope)</option>
                            <option value="27-1">2.7:1 (Ultra Panavision, 2K/4K)</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="ytvideo_title_field" class="form-label"><?php echo Text::_('PLG_EDITORS-XTD_YTVIDEOBTN_LABEL_TITLE'); ?></label>
                        <input name="ytvideotitle" id="ytvideo_title_field" value="" class="form-control" type="text">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="ytvideo_insert_button"><?php echo Text::_('PLG_EDITORS-XTD_YTVIDEOBTN_MODAL_BTN_INSERT'); ?></button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><?php echo Text::_('PLG_EDITORS-XTD_YTVIDEOBTN_MODAL_BTN_CANCEL'); ?></button>
            </div>
        </div>
    </div>
</div>
